name: ana_maria_studio
description: Ana Maria Studio & Academy Flutter app (Android/iOS/Web)
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  firebase_core: ^3.15.2
  firebase_storage: ^12.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.8.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/branding/redlayer_icon_zoom.png
  adaptive_icon_foreground: assets/images/branding/redlayer_icon_zoom.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground_inset: 0
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/branding/
    - assets/images/background/
    - assets/images/background/web/
    - assets/images/background/web/pink_named/
    - assets/images/background/pink/
    - assets/images/background/pink_pages/
    - assets/images/background/pink_named/
    - assets/images/gallery/
    - assets/images/gallery/colors/
    - assets/images/gallery/hairstyles/
    - assets/images/gallery/inspiration/
