// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0ITTYe5eFPnUzIHTVcMSjWLETABdHTM',
    appId: '1:403287487378:web:42c64f23915ef1a68c874b',
    messagingSenderId: '403287487378',
    projectId: 'ana-maria-studio',
    authDomain: 'ana-maria-studio.firebaseapp.com',
    storageBucket: 'ana-maria-studio.firebasestorage.app',
    measurementId: 'G-1412BXNZBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6mXu_riwUPj49J86OqziG5G6bUL42bAY',
    appId: '1:403287487378:android:ee71d810dcd8e9e28c874b',
    messagingSenderId: '403287487378',
    projectId: 'ana-maria-studio',
    storageBucket: 'ana-maria-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZkJU2GwoG4X8XxSFTVU6NHb9BHEv3tN0',
    appId: '1:403287487378:ios:923d1dbb8c0056478c874b',
    messagingSenderId: '403287487378',
    projectId: 'ana-maria-studio',
    storageBucket: 'ana-maria-studio.firebasestorage.app',
    iosBundleId: 'com.anamaria.studio',
  );

}